# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_test <- function() {
    .Call('_hicloudR_rcpp_test', PACKAGE = 'hicloudR')
}

rcpp_readFile <- function(path) {
    .Call('_hicloudR_rcpp_readFile', PACKAGE = 'hicloudR', path)
}

rcpp_updateCalendar <- function(calendar) {
    .Call('_hicloudR_rcpp_updateCalendar', PACKAGE = 'hicloudR', calendar)
}

rcpp_updateNext <- function(vecOld) {
    .Call('_hicloudR_rcpp_updateNext', PACKAGE = 'hicloudR', vecOld)
}

rcpp_tick_data_del_na <- function(dt) {
    invisible(.Call('_hicloudR_rcpp_tick_data_del_na', PACKAGE = 'hicloudR', dt))
}

rcpp_tick_data_add_time_old_version <- function(dt) {
    invisible(.Call('_hicloudR_rcpp_tick_data_add_time_old_version', PACKAGE = 'hicloudR', dt))
}

rcpp_tick_data_cal_delta <- function(dt) {
    invisible(.Call('_hicloudR_rcpp_tick_data_cal_delta', PACKAGE = 'hicloudR', dt))
}

rcpp_updateCZCEInstrumentID <- function(tradingday, oldInstrumentID) {
    .Call('_hicloudR_rcpp_updateCZCEInstrumentID', PACKAGE = 'hicloudR', tradingday, oldInstrumentID)
}

rcpp_simplyCZCEInstrumentID <- function(newInstrumentID) {
    .Call('_hicloudR_rcpp_simplyCZCEInstrumentID', PACKAGE = 'hicloudR', newInstrumentID)
}

rcpp_mbar_from_tick <- function(tick) {
    .Call('_hicloudR_rcpp_mbar_from_tick', PACKAGE = 'hicloudR', tick)
}

rcpp_dbar_from_tick <- function(tick) {
    .Call('_hicloudR_rcpp_dbar_from_tick', PACKAGE = 'hicloudR', tick)
}

